### PR TITLE
feat(sandbox-parallel)

### PR DESCRIPTION
**Pull request by TheExGenesis**
Goals:
- [X] Making the sandbox evaluate in parallel.
- [x] Test speed improvement
- [ ] (unsure whether we should) Installing and using the elm package from the sandbox

Open questions:
- importing `elm.environments.sodaracer.walker.walk_creator import walker_creator` tries to import torch because environments imports diff_models - installing torch on the sandbox would make the container a lot heavier (and iterating potentially slower although caching may help, I haven't tried it)

Notes:
- Imports from the sandbox: we're importing `walker_creator` by copying it into the sandbox. This is not scalable without some more design thought (discussed below).
- Batched returns: if some of items in the batch result in errors, the request code will still be 200, but the result object will contain `unsafe_execute_error_code` and `unsafe_execute_error_message`. Checking for errors will involve checking for these keys in the returned object.

### CODE REVIEW

**Comment by honglu2875** [comment]
@TheExGenesis Maybe we don't need the whole elm in the sandbox. The most modular way is probably to separate sandbox into a different repo and elm depends on that. But it's probably too much for one project. I wonder if there is there a way to only install a subset of dependencies by doing something like `pip install .[sandbox]`? But I don't find a way to subtract dependency in optional packages. Yeah this is a tough question...

**Comment by honglu2875** [comment]
Oh by the way, does https://github.com/CarperAI/OpenELM/blob/main/elm/diff_model.py#L23-L76 duplicate sandbox's codes or is there anything new? When I modified `diff_model.py` I didn't dare to touch those but I think we need to ultimately move them to the right place.

**Comment by TheExGenesis** [comment]
> @TheExGenesis Maybe we don't need the whole elm in the sandbox. The most modular way is probably to separate sandbox into a different repo and elm depends on that. But it's probably too much for one project. I wonder if there is there a way to only install a subset of dependencies by doing something like `pip install .[sandbox]`? But I don't find a way to subtract dependency in optional packages. So yeah your question is tough...

I'm in favor of making the sandbox its own repo but I imagine projects (like us) using the sandbox will want to import stuff like walker_creator in our case.

`"""from elm.environments.sodaracer.walker.walk_creator import walker_creator

def make_square(wc, x0, y0, x1, y1):
    \"\"\"Make a square with top left x0,y0 and top right x1,y1.\"\"\"
    j0 = wc.add_joint(x0, y0)
    j1 = wc.add_joint(x0, y1)
    j2 = wc.add_joint(x1, y1)
    j3 = wc.add_joint(x1, y0)
    return j0, j1, j2, j3


def make_walker():
    wc = walker_creator()

    # the main body is a square
    sides = make_square(wc, 0, 0, 10, 10)
    center = wc.add_joint(5, 5)

    # connect the square with distance muscles
    for k in range(len(sides) - 1):
        wc.add_muscle(sides[k], sides[k + 1])
    wc.add_muscle(sides[3], sides[0])

    # one prong of the square is a distance muscle
    wc.add_muscle(sides[3], center)

    # the other prongs from the center of the square are active
    wc.add_muscle(sides[0], center, 5.0, 0.0)
    wc.add_muscle(sides[1], center, 10.0, 0.0)
    wc.add_muscle(sides[2], center, 2.0, 0.0)

    return wc.get_walker()

"""`

We can make ours work by including the necessary files in the sandbox and importing locally, but whoever's writing the prompts will need to be mindful of the local import.

`from .environments.sodaracer.walker.walk_creator import walker_creator`

I suppose we could write a script that copies local modules (specified in a config file or an argument or a cli prompt) into the container to be imported locally .

> or maybe we have a separate `pyproject.toml` in the walker folder and specifically install that in sandbox?

Well right now I have a Pipfile that informs `pipenv install` inside the container, would it make sense to have a `pyproject.toml` in an inner directory?

**Comment by TheExGenesis** [comment]
> Oh by the way, does https://github.com/CarperAI/OpenELM/blob/main/elm/diff_model.py#L23-L76 duplicate sandbox's codes or is there anything new? When I modified `diff_model.py` I didn't dare to touch those but I think we need to ultimately move them to the right place or delete them.

Sandbox's unsafe_eexecute is slightly modified, I think diff_model's is being used in `DiffModel` but I assume that's temporary

**Comment by TheExGenesis** [comment]
This is funny, I'm testing the parallelism and at least for sodaracers it's not faster
image

**Comment by honglu2875** [comment]
> Well right now I have a Pipfile that informs pipenv install inside the container, would it make sense to have a pyproject.toml in an inner directory?
I think if you just copy that part into the container and run install, it could work. Not sure if it's good practice. The only argument I can see against is that if we want to massively scale the simulator and the walker stuff, things could become awkward. But maybe we won't get to that point?

**Comment by honglu2875** [comment]
> This is funny, I'm testing the parallelism and at least for sodaracers it's not faster image

I usually use Pool and then map to a list of arguments. Not familiar with this ProcessPoolExecutor. 

Also, did you print out cpu count to make sure all cpu can be used?

**Comment by TheExGenesis** [comment]
> > This is funny, I'm testing the parallelism and at least for sodaracers it's not faster image
> 
> I usually use Pool and then map to a list of arguments. Not familiar with this ProcessPoolExecutor.
> 
> Also, did you print out `cpu_count` to make sure all cpu can be used? If you run on the cpu cluster, there might be something tricky (like you need to pass --cpus_per_task). Also while it runs, try to open up another terminal and do `top` (and then F1) or `htop` to monitor the cpu usage.

it works the same way, just as a context. Trying it with another function like finding fibonnaci numbers works as expected, it's only with executing code that it's slower.

**Pull request closed without merging**
