### PR TITLE
Image gen

### PR DESCRIPTION
**Pull request by honglu2875**
This is based on #9. A separate sandbox container also need to run behind. It assumes an endpoint to run codes in the sandbox and return the result of a specific function. It contacts the sandbox server via the lines
```python
x = requests.post(f"http://{self.sandbox_server}/eval_func", json={"code": code, "func_name": self.func_name}, timeout=5)
result = np.array(json.loads(x.text))
```
This can be changed later when the sandbox is merged. But some API like this is needed.

Still working on
- [x] Finish debugging the `ImageOptim` environment.
- [x] Test and debug the integration with elm.

### CODE REVIEW

**Comment by honglu2875** [comment]
Screenshot from 2022-10-13 04-44-33
Now it runs, but quite slowly. Either I did something stupid or I simply need to make a batch version of MAPElite.

For the behavior space, I simply cut the image up into smaller regions (`block_size`) and take the mean. The default is 16x16 in 32x32 images which result in pretty high dimension of behavior space (3 channels x 4 x 4). We can also simply make `block_size` to be 32x32 and turn up `n_bins` just to separate the overall colors. Maybe there will be some fun results.

It's probably ready to merge (into #9 of course) after review if speed doesn't matter. But I will think about improvements and do more experiments along the way.

**Comment by herbiebradley** [comment]
Now that #9 is merged I think this one is good to merge now, thanks for the great work! 🚀

**Comment by honglu2875** [comment]
> Now that #9 is merged I think this one is good to merge now, thanks for the great work! rocket

Let me make one more quick change and it will be ready.

**Comment by honglu2875** [comment]
Reverted some bad commits. It runs and it looks alright. I guess a lot need to be cleaned up anyway once we fix a code style, have a CI and start to write unit tests.
Just a few notes:
- Added `use_batch_op` to the `BaseEnvironment` and now env both with and without batch exist. The difference is just whether we can pass in a `batch_size` argument and whether the outputs of `.random()` and `.mutate()` should be lists. Do we simply change all other envs (function and string) to conform with env with batch (like batch_size=1)? This should be a super easy update that cleans up a lot of codes, but I leave it just in case.
- I'm saving the most recent bad mutations in `MAPElites.recycled` now, but I don't do anything with it. We can add stuff later if we want to make use of it. 
- I have a `behaviour_mode_spec` dict in the environment. We can try other definitions of behaviour spaces by adding to it.
- The prompt format for mutations is not really optimized. It does produce new mutations so I guess it's good for now.

**Comment by herbiebradley** [comment]
> * Added `use_batch_op` to the `BaseEnvironment` and now env both with and without batch exist. The difference is just whether we can pass in a `batch_size` argument and whether the outputs of `.random()` and `.mutate()` should be lists. Do we simply change all other envs (function and string) to conform with env with batch (like batch_size=1)? This should be a super easy update that cleans up a lot of codes, but I leave it just in case.

Good idea, can you quickly add this to this PR for convenience?

Thanks for the work!

**Comment by honglu2875** [comment]
> > * Added `use_batch_op` to the `BaseEnvironment` and now env both with and without batch exist. The difference is just whether we can pass in a `batch_size` argument and whether the outputs of `.random()` and `.mutate()` should be lists. Do we simply change all other envs (function and string) to conform with env with batch (like batch_size=1)? This should be a super easy update that cleans up a lot of codes, but I leave it just in case.
> 
> Good idea, can you quickly add this to this PR for convenience?
> 
> Thanks for the work!

No problem. Will do it tomorrow morning.

**Comment by honglu2875** [comment]
Now it's done. Reduced the steps of function optim environment for faster testing. Still a lot of stuff to improve for these toy tasks but I guess we do it later.

For `ImageOptim` to run, we will still need an api from sandbox though. In my setup I made my own quick-and-dirty change so that it runs. I will leave a message in the sandbox branch.

**Review by herbiebradley — APPROVED** [review]

**Pull request merged**
